fix errors in build script and removed install requirements file in conda flavor because one of the dependencies caused a build error of the udfclient

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,4 +1,8 @@
 #!/usr/bin/env bash
+#set -e
+
+#bash clean
+
 die() { echo "ERROR:" "$@" >&2; exit 1; }
 
 if [[ "$OSTYPE" == "darwin"* ]]; then
@@ -25,13 +29,14 @@ done
 [ "X$FLAVOR" = "X" ] && die "Missing mandatory argument --flavor"
 
 TMPDIR=$(mktemp -d `basename $0`_${FLAVOR}_tmpdir.XXXXXXXX)
-function cleanup {
-    if [ ! -z "$TMPDIR" ]; then
-    	rm -rf $TMPDIR
-    fi
-}
+#TMPDIR=builds
+# function cleanup {
+#     if [ ! -z "$TMPDIR" ]; then
+#     	rm -rf $TMPDIR
+#     fi
+# }
 
-trap cleanup EXIT
+# trap cleanup EXIT
 
 if [[ "$OSTYPE" == "darwin"* ]]; then
         CORES=$(sysctl -n hw.ncpu)
@@ -41,7 +46,7 @@ fi
 
 REPNAME=$(echo "$FLAVOR" | tr '[:upper:]' '[:lower:]')
 
-BUILD_DIR=builds/build
+BUILD_DIR=$TMPDIR/build
 mkdir -p $BUILD_DIR
 echo Using base docker file: Dockerfile.base_$FLAVOR
 cp -r ext flavors/$FLAVOR/* src $BUILD_DIR
@@ -51,9 +56,10 @@ ls $BUILD_DIR
 echo Using build docker file: Dockerfile.build_$FLAVOR
 (cd  $BUILD_DIR && docker build . --tag exaudf/build_$REPNAME -f Dockerfile.build_$FLAVOR || die "Could not create exaudf/build")
 
-EXTRACT_DIR=extract
+EXTRACT_DIR=extract/
 PATH_EXTRACT_DIR=$BUILD_DIR/$EXTRACT_DIR
-mkdir -p $EXTRACT_DIR
+#rm -r $PATH_EXTRACT_DIR
+mkdir -p $PATH_EXTRACT_DIR
 docker container create --name extract_$REPNAME exaudf/build_$REPNAME
 docker container cp extract_$REPNAME:/exaudf $PATH_EXTRACT_DIR
 docker container rm -f extract_$REPNAME
